import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./component/nav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ToastContainer
					position="top-center"
					autoClose={2000}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick={true}
					theme="dark"
				/>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
